### ISSUE TITLE
[improve] Add a TTL setup to issues

### ISSUE THREAD

**Issue by nimbinatus** [Austin-Devops/atxdevops-job-board#7]
One thing that might make this board a bit more useful would be to add an Action that marks a job post (issue) as stale and then closes it after a certain period of time so that roles don't stay up forever. Maybe something like https://github.com/actions/stale?

cc @jjasghar and anyone else with a thought on this

**Comment by zfouts** [comment]
I like that idea @nimbinatus

What actions do we need to take to get this started?

**Comment by jjasghar** [comment]
I think it's just adding the github action.

maybe something like this? 90 days and 10 days close after? so a total 100 days?

```yaml
name: "Close stale issues"
on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is stale because it has been open 90 days with no activity. Remove stale label or comment or this will be closed in 10 days'
        days-before-stale: 90
        days-before-close: 10
```
